### ISSUE TITLE
How could I get  UsageStatsResource by plugin of graylog-plugin-anonymous-usage-statistics?

### ISSUE THREAD

**Issue by a8726426** [Graylog2/graylog-plugin-anonymous-usage-statistics#16]
Hello！
    I added the plugin of graylog-plugin-anonymous-usage-statistics to my graylog-server with version 1.1.0,but could not find  UsageStatsResource on the page of http://127.0.0.1:12900/api-browser neither could access the method of UsageStatsResource  with the url. How can I get the restresouce by the plugin?

**Comment by kroepke** [comment]
Hey, the API browser in 1.1 did not properly show plugin resources, iirc, and additionally only the very first version of this plugin would be compatible with 1.1.0 anyway.

Most likely the plugin failed to load during start. Please upgrade to the latest release version 1.3.4, which already ships with the plugin bundled.

Thanks,
Kay

**Comment by a8726426** [comment]
Thanks for your reply ! Now I run a graylog-server with version of 1.3.4 and the plugin of usage-statistics-1.2.2.jar has been installed in the server.But I got "{"type":"ApiError","message":"HTTP 404 Not Found"}" after entering  "http://127.0.0.1:12900/node"  into the browser . How can I access the  method in UsageStatsResource?

**Comment by a8726426** [comment]
Thanks for your reply  ! Now I run a graylog-server with version of 1.3.4 and the plugin of usage-statistics-1.2.2.jar has been installed in the server.But I got "{"type":"ApiError","message":"HTTP 404 Not Found"}" after entering "http://127.0.0.1:12900/node" into the browser . How can I access the method in UsageStatsResource?

**Comment by joschi** [comment]
@a8726426 HTTP resources provided by plugins are available under another namespace. Please refer to the API Browser of Graylog 1.3.x for the specific URI.
