### ISSUE TITLE
Test functionality against Graylog 2.3.0 with Elasticsearch HTTP client

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-anonymous-usage-statistics#22]
Make sure that the plugin wasn't broken by any changes during the migration from the Elasticsearch node client to Jest.

**Comment by bernd** [comment]
@joschi @dennisoelkers Has this happened?

**Comment by bernd** [comment]
@joschi @dennisoelkers Ping

**Comment by joschi** [comment]
Seems to work without problems with Graylog 2.3.0-beta.1 and ES 2.4.5 and ES 5.3.0.

**Comment by bernd** [comment]
@joschi Thank you! :smiley:
