### ISSUE TITLE
Cluster status issue for stream, user and output count fields

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-anonymous-usage-statistics#6]
It looks like there is an issue with the `stream_rule_count`, `user_count`, and `output_count` fields in the clusters information. Because they always report as `0`.

**Comment by joschi** [comment]
I can't reproduce this. The data points you've mentioned are filled (and correct) in my test setups.

You can check the output via http://127.0.0.1:12900/plugins/org.graylog.plugins.usagestatistics/cluster?pretty=true on your local machine.
