### ISSUE TITLE
Collect 5min average of throughput

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-anonymous-usage-statistics#9]
The throughput reporting should ideally report 5min average values additionally to the `1-sec-rate` and `total`. Reason is that the `total` value is hard to make sense of given that the server might have been rebooted between collections and the `1-sec-rate` is way to flaky.

**Comment by kroepke** [comment]
I'm not sure what we are looking for here.
The 1 second rate is completely useless and shouldn't be reported at all, imho, it adds not information.

Each collection also reports the uptime of the server, so the total is reliable, although maybe slightly more difficult to calculate.

Sample the 5 minute rate assumes that throughput is steady and sampling this number every 6 hours does not add any value either, at least I can't see what information it would provide that the total and uptime does not already give us.

If anything the plugin could report the rate over the entire reporting period (but then it already does that implicitly). At least with a reporting period of 6 hours I don't think any rate would give us more information about usage.
Comments?

**Comment by lennartkoopmann** [comment]
Hmmm... If you can build a reliable query with the `uptime` and `total` then I am fine with that. I'll leave it to your judgement if this is sufficient and trust your opinion on it. :)

Fully agree that we should remove the `1-sec-rate` for sure. This will just lead to drawing wrong conclusions if one is not aware of the domain (how it was collected and what it means).
